ORT_VERSION="${1:-1.14.0}"
echo "ORT_VERSION=${ORT_VERSION}"
cmake -GXcode -Bbuild.ios -DCMAKE_TOOLCHAIN_FILE=./ios-toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=OFF -DENABLE_VISIBILITY=ON -DUSE_ORT=$ORT_VERSION
